# Execute sanity checks
name: check

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: poetry-lock --all-files

  packaging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: build package
        run: poetry build
